In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
df = pd.read_csv('Marks-MEP-102.csv')

In [18]:
df.head()

,f,ID No.,Name,Discipline,Institute Email ID,Batch,Sketching and Drawing Lab 1\n30 Marks,Sketching and Drawing Lab 2\n40 Marks,Sketching and Drawing Lab 3\n30 Marks,solid edge1\n30 Marks,...,3-d printing,laser cutting,welding,End sem (out of 100),Assignment mark (out of 40),Mid sem (out of 30),End sem (out of 30),Total,Grade,Unnamed: 28
0,89,B25DS029,PANDU HARSHITHA,Data Science and Artificial Intelligence,panduharshi@iitbhilai.ac.in,Batch 2,26.0,38.0,30.0,29.0,...,9,8,10,100.0,30.454545,29.188688,30.0,90,A+,NaN
1,54,B25CS055,SUBHAMKAR SAHU,Computer Science and Engineering,subhamkars@iitbhilai.ac.in,Batch 2,25.0,39.0,29.0,30.0,...,9,9,10,100.0,29.969697,29.067760,30.0,89,A,NaN
2,243,B25ME013,ASHTAPUTRE ANANYA ABHAY,Mechanical Engineering,aaabhay@iitbhilai.ac.in,Batch 6 A,28.5,38.0,29.0,28.0,...,9,8,10,100.0,30.878788,28.093905,30.0,89,A,NaN
3,307,B25MT024,SAMAYANA MAHESH GODBOLE,Mechatronics Engineering,smgodbole@iitbhilai.ac.in,Batch 3,25.0,36.0,30.0,30.0,...,10,9,8,100.0,30.454545,28.422257,30.0,89,A,NaN
4,87,B25DS027,NITISHA DESHMUKH,Data Science and Artificial Intelligence,nitishadesh@iitbhilai.ac.in,Batch 2,28.0,39.0,27.0,28.0,...,10,9,A,100.0,30.181818,28.184997,30.0,88,A,NaN

In [19]:
df.isnull().mean()*100

f                                          0.000000
ID No.                                     0.000000
Name                                       0.000000
Discipline                                 0.321543
Institute Email ID                         0.321543
Batch                                      0.000000
Sketching and Drawing Lab 1\n30 Marks      0.964630
Sketching and Drawing Lab 2\n40 Marks      1.286174
Sketching and Drawing Lab 3\n30 Marks      0.964630
solid edge1\n30 Marks                      1.286174
solid edge 2 \n30 Marks                    1.607717
Solid Edge 3\n30 Marks                     1.286174
Solid Edge 4\n30 Marks                     4.501608
Solid Edge  exam\n60 Marks                 0.964630
Exam-mid sem                               0.000000
Set                                        0.000000
Normalized score (out of 47)               0.000000
Unnamed: 17                               96.784566
cnc                                        1.286174
3-d printing                               1.929260
laser cutting                              1.929260
welding                                    0.321543
End sem (out of 100)                       0.321543
Assignment mark (out of 40)                0.000000
Mid sem (out of 30)                        0.000000
End sem (out of 30)                        0.000000
Total                                      0.000000
Grade                                      0.000000
Unnamed: 28                               99.356913
dtype: float64

In [23]:
df.shape

(311, 29)

In [31]:
cols = [var for var in df.columns if df[var].isnull().mean() < 0.05 and df[var].isnull().mean() > 0]
len(cols)

15

In [32]:
df[cols].sample(15)

,Discipline,Institute Email ID,Sketching and Drawing Lab 1\n30 Marks,Sketching and Drawing Lab 2\n40 Marks,Sketching and Drawing Lab 3\n30 Marks,solid edge1\n30 Marks,solid edge 2 \n30 Marks,Solid Edge 3\n30 Marks,Solid Edge 4\n30 Marks,Solid Edge exam\n60 Marks,cnc,3-d printing,laser cutting,welding,End sem (out of 100)
113,Mechanical Engineering,smistry@iitbhilai.ac.in,20.5,34.0,27.5,29.0,27.0,27.0,30.0,60.0,9.0,10,10,7,100.0
238,Electronics and Communication Engineering,rsaini@iitbhilai.ac.in,17.0,NaN,24.0,26.0,26.0,27.0,28.0,45.0,NaN,9,--,8,100.0
262,Materials Science and Metallurgical Engineering,thussain@iitbhilai.ac.in,22.5,34.0,24.0,28.0,26.0,28.0,30.0,60.0,NaN,9,9,8,95.0
49,Computer Science and Engineering,namanayush@iitbhilai.ac.in,26.0,39.0,23.0,28.0,30.0,26.0,29.0,55.0,9.0,9,8,10,100.0
223,Mechanical Engineering,smandal@iitbhilai.ac.in,21.5,38.0,23.0,29.0,28.0,29.0,29.0,54.0,9.0,8,9,7,95.0
29,Mechatronics Engineering,amraynil@iitbhilai.ac.in,22.5,36.5,25.5,28.0,27.0,27.0,29.0,55.0,9.0,10,9,8,100.0
251,Computer Science and Engineering,kollivenkata@iitbhilai.ac.in,26.0,33.0,26.0,15.0,28.0,26.0,27.0,55.0,9.0,9,9,9,90.0
144,Computer Science and Engineering,palavalasapaw@iitbhilai.ac.in,23.0,21.0,19.0,18.0,28.0,26.0,28.0,58.0,9.0,9,8,9,95.0
260,Electrical Engineering,kamireddybha@iitbhilai.ac.in,19.0,28.0,24.0,29.0,28.0,27.0,28.0,60.0,9.5,9,9,7,100.0
285,Mechanical Engineering,rsoni@iitbhilai.ac.in,21.0,32.0,26.0,30.0,28.0,28.0,30.0,55.0,9.0,8,8,7,100.0
193,Computer Science and Engineering,harshvince@iitbhilai.ac.in,27.0,34.0,23.0,22.0,20.0,28.0,21.0,52.0,8.0,8,9,9,90.0
253,Electrical Engineering,penubodimanoj@iitbhilai.ac.in,19.5,30.0,23.0,26.0,28.0,26.0,27.0,60.0,9.0,9,9,8,100.0
10,Mechatronics Engineering,jalaj@iitbhilai.ac.in,24.5,39.0,29.0,27.0,28.0,30.0,28.0,60.0,9.0,10,8,9,95.0
259,Computer Science and Engineering,shreyanshpra@iitbhilai.ac.in,23.0,32.0,23.0,18.0,20.0,24.0,30.0,60.0,8.0,8,9,10,100.0
91,Data Science and Artificial Intelligence,harshitashuk@iitbhilai.ac.in,27.5,32.0,22.0,28.0,26.0,28.0,27.0,54.0,10.0,9,8,10,100.0

In [33]:
len(df[cols].dropna())/len(df)

0.8906752411575563

In [35]:
new_df = df[cols].dropna()
df.shape, new_df.shape

((311, 29), (277, 15))

In [ ]:
new_df.hist(bins=50, density=True, figsize=(12, 12))